# Generated by Django 5.2.7 on 2025-11-10 20:47

import django.db.models.deletion
import django.utils.timezone
import listings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('bedrooms', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('property_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('background_image', models.ImageField(help_text='Recommended size: 1920x800px', storage=listings.models.PageContentStorage(), upload_to='hero/')),
                ('button_text', models.CharField(default='Browse Properties', max_length=50)),
                ('button_link', models.CharField(default='/properties/', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['order', '-is_active'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('api', 'API Import')], default='manual', max_length=20)),
                ('api_id', models.CharField(blank=True, help_text='External API ID', max_length=100, null=True)),
                ('title', models.CharField(default='New Property Listing', max_length=200)),
                ('description', models.TextField(default='Property description')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('address', models.CharField(default='123 Main Street', max_length=255)),
                ('city', models.CharField(default='Killeen', max_length=100)),
                ('state', models.CharField(default='TX', max_length=50)),
                ('zip_code', models.CharField(blank=True, default='76541', max_length=10)),
                ('beds', models.IntegerField(default=3)),
                ('baths', models.DecimalField(decimal_places=1, default=2.0, max_digits=3)),
                ('sq_ft', models.IntegerField(blank=True, default=1500, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='properties/main/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('properties', 'Properties Page')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('header_image', models.ImageField(blank=True, null=True, storage=listings.models.PageContentStorage(), upload_to='page-headers/')),
                ('content', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about', 'About Section'), ('services', 'Services Section'), ('testimonials', 'Testimonials'), ('cta', 'Call to Action'), ('features', 'Features'), ('contact_info', 'Contact Information')], max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, storage=listings.models.PageContentStorage(), upload_to='section-content/')),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Content',
                'verbose_name_plural': 'Section Contents',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, storage=listings.models.PageContentStorage(), upload_to='site-settings/')),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, storage=listings.models.PageContentStorage(), upload_to='testimonials/')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Raja Ram Gautam', max_length=100)),
                ('title', models.CharField(default='Senior Real Estate Specialist', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agents/')),
                ('rating', models.DecimalField(decimal_places=1, default=4.7, max_digits=3)),
                ('review_count', models.IntegerField(default=128)),
                ('properties_sold', models.CharField(default='500+', max_length=50)),
                ('client_satisfaction', models.CharField(default='98%', max_length=50)),
                ('years_experience', models.CharField(default='15+', max_length=50)),
                ('phone', models.CharField(default='(555) 123-4567', max_length=20)),
                ('email', models.EmailField(default='raja@veteransrealty.com', max_length=254)),
                ('description', models.TextField(default='Welcome to Veterans Realty, where your home journey begins with confidence and trust. Our lead realtor is one of the most talented, well-experienced, and highly professional agents in the Central Texas area.')),
                ('areas_of_expertise', models.TextField(default='Residential Home Sales and Purchases\nVA and FHA Loan Support\nMilitary Relocation Assistance (Fort Cavazos Area)\nInvestment and Rental Properties\nNew Construction & First-Time Home Buyers', help_text='Enter each area of expertise on a new line')),
                ('why_choose', models.TextField(default='Highly Experienced: Proven track record of successful home sales and purchases.\nProfessional & Reliable: Trusted by clients for his honesty and clear communication.\nLocal Market Expert: Deep knowledge of Fort Cavazos, Killeen, Harker Heights, and Copperas Cove.\nMilitary Friendly: Dedicated to supporting our service members and their families.', help_text='Enter each reason on a new line, format: Title: Description')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/additional/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='listings.listing')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
