# Generated by Django 5.2.7 on 2026-01-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=20)),
                ('budget', models.CharField(max_length=50)),
                ('timeline', models.CharField(max_length=50)),
                ('pre_approved', models.CharField(max_length=50)),
                ('bedrooms', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=20)),
                ('timeline', models.CharField(max_length=50)),
                ('estimated_value', models.CharField(max_length=50)),
                ('agent_experience', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
