# Generated by Django 5.2.7 on 2026-01-11 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_buyerlead_sellerlead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=20)),
                ('timeline', models.CharField(choices=[('immediately', 'Immediately'), ('1-3 months', '1-3 Months'), ('3-6 months', '3-6 Months'), ('6+ months', '6+ Months'), ('just exploring', 'Just Exploring Options')], max_length=20)),
                ('budget', models.CharField(blank=True, choices=[('under-250k', 'Under $250,000'), ('250k-500k', '$250,000 - $500,000'), ('500k-1m', '$500,000 - $1 Million'), ('1m-2m', '$1 Million - $2 Million'), ('over-2m', 'Over $2 Million')], max_length=20)),
                ('pre_approved', models.CharField(blank=True, max_length=20)),
                ('bedrooms', models.CharField(blank=True, max_length=10)),
                ('property_value', models.CharField(blank=True, max_length=20)),
                ('agent_experience', models.CharField(blank=True, max_length=20)),
                ('property_condition', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BuyerLead',
        ),
        migrations.DeleteModel(
            name='SellerLead',
        ),
    ]
