# Generated by Django 5.2.7 on 2026-01-12 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_propertyinterest_delete_buyerlead_delete_sellerlead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinterest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyinterest',
            name='contacted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyinterest',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyinterest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertyinterest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='propertyinterest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('qualified', 'Qualified'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinterest',
            name='agent_experience',
            field=models.CharField(blank=True, choices=[('yes-currently', 'Yes, Currently Working With One'), ('yes-past', 'Yes, In The Past'), ('no', 'No, This Is My First Time')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinterest',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('studio', 'Studio'), ('1', '1 Bedroom'), ('2', '2 Bedrooms'), ('3', '3 Bedrooms'), ('4+', '4+ Bedrooms')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyinterest',
            name='pre_approved',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('working-on-it', 'Working On It'), ('cash-buyer', 'Cash Buyer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinterest',
            name='property_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent - Recently Renovated'), ('good', 'Good - Well Maintained'), ('average', 'Average - Needs Some Updates'), ('needs-work', 'Needs Work - Significant Updates Required')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinterest',
            name='property_value',
            field=models.CharField(blank=True, choices=[('under-250k', 'Under $250,000'), ('250k-500k', '$250,000 - $500,000'), ('500k-1m', '$500,000 - $1 Million'), ('1m-2m', '$1 Million - $2 Million'), ('over-2m', 'Over $2 Million')], max_length=20),
        ),
    ]
