# Generated by Django 5.2.7 on 2026-01-24 05:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_propertyinterest_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('category', models.CharField(choices=[('buying', 'Buying Experience'), ('selling', 'Selling Experience'), ('military', 'Military Relocation'), ('first_time', 'First-Time Home Buyer'), ('investment', 'Investment Property'), ('general', 'General Experience')], default='general', max_length=50)),
                ('comment', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('property_related', models.CharField(blank=True, help_text='Property or service mentioned in review', max_length=200, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Review',
                'verbose_name_plural': 'Client Reviews',
                'ordering': ['-created_at', '-featured'],
            },
        ),
    ]
