# Generated by Django 5.2.7 on 2026-05-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_showcase/')),
                ('image_alt', models.CharField(default='Luxury Modern House', max_length=150)),
                ('quote', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
