# Generated by Django 5.2.7 on 2026-05-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_homeshowcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='hero/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Image',
                'verbose_name_plural': 'Home Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='HomeShowcase',
        ),
    ]
